debug = true
log_level = "info"

[server_config]
host = "127.0.0.1"
port = 8082

# 数据库配置
[database]
name = "analyst"
types = "mysql"
host = "127.0.0.1"
port = 3306
username = "root"
database = "house"
password = "a123456"